
<Contenedor>:

    #propiedades del grid
    cols: 7
    rows: 4
    spacing: 10
    padding: 5
    
    Button: 
        id: button_7
        text: "7"
        size: [150, 140]
        
    Button: 
        id: button_8
        text: "8"
        size: [150, 140]
        
    Button: 
        id: button_9
        text: "9"
        size: [150, 140]
        
    Button: 
        id: button_borrar
        text: "Borrar"
        size: [150, 140]
